name: Export Drum Set Images

on:
  workflow_dispatch:
  push:
    paths:
      - 'Diagrams/DrumSet/DrumSet.drawio'

permissions:
  contents: write

jobs:
  export-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Draw.io Desktop CLI
        run: |
          sudo apt update
          sudo apt install snapd
          sudo snap install drawio

      - name: Export Drum Set layer to DrumSet.png
        run: |
          drawio --export --output "Assets/DrumSet.png" --format png --layer "Drum Set" "Diagrams/DrumSet/DrumSet.drawio"

      - name: Export Drum Set and Input Map layers to InputMap.png
        run: |
          drawio --export --output "Assets/InputMap.png" --format png --layer "Drum Set" --layer "Input Map" "Diagrams/DrumSet/DrumSet.drawio"

      - name: Commit changes to repo
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Automatically uploaded new assets from Drum Set.drawio
          commit_user_name: ${{ vars.COMMIT_USER_NAME }}
          commit_user_email: ${{ vars.COMMIT_USER_EMAIL }}
          commit_author: ${{ vars.COMMIT_AUTHOR }}
          push_options: '--force'
