name: Export Drum Set PNG

on:
  push:
    paths:
      - 'Diagrams/DrumSet/Drum Set.drawio'

jobs:
  export-drum-set-png:
    runs-on: ubuntu-latest
    env:
      DRAWIO_FILE: Diagrams/DrumSet/Drum Set.drawio
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Export Drum Set layer as PNG
        uses: severgroup-tt/actions-drawio-cli@v0.0.2
        with:
          source: ${{ env.DRAWIO_FILE }}
          destination: Assets/DrumSet.png
          format: png
        #   layer: Drum Set

      - name: Export Drum Set and Item Map layers as PNG
        uses: severgroup-tt/actions-drawio-cli@v0.0.2
        with:
          source: ${{ env.DRAWIO_FILE }}
          destination: Assets/ItemMap.png
          format: png
        #   layer: Drum Set
        #   layer2: Item Map

      - name: Commit changes to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automatically uploaded new assets from Drum Set.drawio
          commit_user_name: ${{ vars.COMMIT_USER_NAME }}
          commit_user_email: ${{ vars.COMMIT_USER_EMAIL }}
          commit_author: ${{ vars.COMMIT_AUTHOR }}
          push_options: '--force'
