name: Export Drum Set Images

on:
  workflow_dispatch:
  push:
    paths:
      - 'Diagrams/DrumSet/DrumSet.drawio'

permissions:
  contents: write

jobs:
  export-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Draw.io Desktop CLI and Xvfb)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxml2-utils libnotify4 libsecret-1-0
          wget -O drawio.deb https://github.com/jgraph/drawio-desktop/releases/download/v27.0.9/drawio-amd64-27.0.9.deb
          sudo dpkg -i drawio.deb

      - name: Check for DrumSet.drawio file
        run: |
          if [ ! -f "Diagrams/DrumSet/DrumSet.drawio" ]; then
            echo "ERROR: Diagrams/DrumSet/DrumSet.drawio not found!" >&2
            exit 1
          fi

      - name: Debug - List files in Diagrams/DrumSet
        run: ls -lR Diagrams/DrumSet

      - name: Debug - Find drawio binary
        run: |
          which drawio || true
          which drawio-desktop || true
          ls -l /opt/drawio || true

      - name: Export Drum Set layer to DrumSet.png
        run: |
          if command -v drawio-desktop > /dev/null; then
            xvfb-run drawio-desktop --export --output "Assets/DrumSet.png" --format png --layer "Drum Set" "Diagrams/DrumSet/DrumSet.drawio"
          else
            xvfb-run drawio --export --output "Assets/DrumSet.png" --format png --layer "Drum Set" "Diagrams/DrumSet/DrumSet.drawio"
          fi

      - name: Export Drum Set and Input Map layers to InputMap.png
        run: |
          if command -v drawio-desktop > /dev/null; then
            xvfb-run drawio-desktop --export --output "Assets/InputMap.png" --format png --layer "Drum Set" --layer "Input Map" "Diagrams/DrumSet/DrumSet.drawio"
          else
            xvfb-run drawio --export --output "Assets/InputMap.png" --format png --layer "Drum Set" --layer "Input Map" "Diagrams/DrumSet/DrumSet.drawio"
          fi

      - name: Commit changes to repo
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Automatically uploaded new assets from Drum Set.drawio
          commit_user_name: ${{ vars.COMMIT_USER_NAME }}
          commit_user_email: ${{ vars.COMMIT_USER_EMAIL }}
          commit_author: ${{ vars.COMMIT_AUTHOR }}
          push_options: '--force'
          file_pattern: '**/*.png'
